In [ ]:
import time
print(time.ctime())
# time.ctime()

Thu Feb 15 06:53:55 2024


In [ ]:
x=1
y=x+2
x=3
y

3

1. strings --> text data
2. integer --> int num
3. float -->
4. boolean -->
5. complex -->

In [ ]:
# NUMPY = number phyton --> import library di phyton
import numpy as np


In [ ]:
x=np.array([1,4,3])
x

array([1, 4, 3])

In [ ]:
[1,4,3]

[1, 4, 3]

In [ ]:
y=np.array([[1,4,3], [9,2,7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [ ]:
def sum(a,b,c):
  # function sum 3 inputed num --> output: a+b+c

  # out=a+b+c
  return a+b+c

In [ ]:
sum(1,2,3)

6

In [ ]:
1+2+3

6

In [ ]:
def add(a,b):
  if(a>b):
    print("a lebih besar dari b")
  elif(a<b):
    print("a lebih kecil dari b")
  else:
    print("a sama dengan b")


In [ ]:
add(3,4)
add(0,0)
add(-9,-9)

a lebih kecil dari b
a sama dengan b
a sama dengan b


In [ ]:
def my_therm(temp, desired_temp):
  if temp < desired_temp-5:
    status='Heat'
  elif temp > desired_temp+5:
    status='AC'
  else:
    status='off'
  return status
  # kalau tidak ada return maka hasil adalah none karena tidak ada nilai yang dikembalikan, kecuali menggunakkan print maka langsung dicetak

In [ ]:
status=my_therm(65,75)
print(status)

Heat


In [ ]:
x=1.5
if x>1 and x<2:
  y=2
elif 2<x<4:
  y=4
else:
  y=0
print(y)

2


In [ ]:
string = "aabbcc"

In [ ]:
print(string)

aabbcc


In [ ]:
myBoolean=False

In [ ]:
myBoolean

False

In [ ]:
x=float(5)
x

5.0

In [ ]:
x="Hello, world"

In [ ]:
print(x.upper())

# cetak dari index 0 sampai ke 5
print(x[:5])
print(x[2:5])

HELLO, WORLD
Hello
llo


In [ ]:
x="Hello"
y=" world"

In [ ]:
print(x+y)

Hello world


In [ ]:
x=np.array([[1,2,3], [4,5,6]])
y=np.array([[1,1,1], [2,2,2]])

In [ ]:
print(x+y)

[[2 3 4]
 [6 7 8]]


In [ ]:
a=np.array([[4,5], [6,7]])
b=np.array([[8,9], [10,11]])

In [ ]:
print(a@b)

print(a*b)
# @ untuk mengalikan array
#  kalau * hanya untuk mengalikan baris biasa

[[ 82  91]
 [118 131]]
[[32 45]
 [60 77]]


In [ ]:
x=np.array([[2,3], [5,10], [11,17]])
y=np.array([[10,12,11,14], [7,6,3,2]])

In [ ]:
x@y

array([[ 41,  42,  31,  34],
       [120, 120,  85,  90],
       [229, 234, 172, 188]])